// Generated by tools/build-web.cjs — do not edit by hand.
// Offline shell: precache every game file; network-first for same-origin so updates land, cache fallback offline.
const CACHE = 'ozymandosis-e0007d538c';
const FILES = [
 "./",
 "./css/app.css",
 "./docs/concept.html",
 "./icon.svg",
 "./icons/favicon-64.png",
 "./icons/icon-192.png",
 "./icons/icon-512.png",
 "./icons/maskable-512.png",
 "./index.html",
 "./js/bench.js",
 "./js/core/audio.js",
 "./js/core/crash.js",
 "./js/core/music.js",
 "./js/core/profile.js",
 "./js/core/seed.js",
 "./js/core/store.js",
 "./js/core/util.js",
 "./js/data/chassis.js",
 "./js/data/organs.js",
 "./js/data/specials.js",
 "./js/data/techs.js",
 "./js/native.js",
 "./js/net/audit.js",
 "./js/net/net.js",
 "./js/net/online.js",
 "./js/render/anatomy.js",
 "./js/render/backend.js",
 "./js/render/core.js",
 "./js/render/gl/atlas.js",
 "./js/render/gl/batches.js",
 "./js/render/gl/glrenderer.js",
 "./js/render/gore.js",
 "./js/render/gpu/gpurenderer.js",
 "./js/render/look.js",
 "./js/render/menuscene.js",
 "./js/render/minimap.js",
 "./js/render/renderer.js",
 "./js/sim/ai.js",
 "./js/sim/mapgen.js",
 "./js/sim/stats.js",
 "./js/sim/world.js",
 "./js/ui/codex.js",
 "./js/ui/dom.js",
 "./js/ui/forge.js",
 "./js/ui/game.js",
 "./js/ui/icons.js",
 "./js/ui/menus.js",
 "./js/ui/perf.js",
 "./js/ui/tech.js",
 "./manifest.webmanifest",
 "./title.html",
 "./vendor/fonts/AtkinsonMono-normal.woff2",
 "./vendor/fonts/AtkinsonNext-italic.woff2",
 "./vendor/fonts/AtkinsonNext-normal.woff2",
 "./vendor/fonts/Cinzel-normal.woff2",
 "./vendor/fonts/CinzelDecorative-700.woff2",
 "./vendor/fonts/fonts.css",
 "./vendor/three.min.js",
 "./vendor/three.webgpu.min.js"
];
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.pathname === '/ws' || u.origin !== location.origin) return;
  e.respondWith(fetch(e.request).then(r => { if (r.ok) { const c = r.clone(); caches.open(CACHE).then(k => k.put(e.request, c)); } return r; })
    .catch(() => caches.match(e.request, { ignoreSearch: true }).then(m => m || caches.match('./index.html'))));
});
