#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Distribution build (the game itself needs no build step):
//  1. regenerates sw.js with the exact precache list and a content-hash version,
//  2. stages the web app in www/ (the PWA artifact, and Capacitor's webDir).
//   node tools/build-web.cjs
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.join(__dirname, '..'), WWW = path.join(ROOT, 'www');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const refs = [...html.matchAll(/(?:src|href)="([^"#?:]+)"/g)].map(m => m[1]).filter(f => !f.startsWith('http') && !f.startsWith('data:') && fs.existsSync(path.join(ROOT, f)));
const extra = ['index.html', 'title.html', 'manifest.webmanifest', 'icon.svg', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png', 'icons/favicon-64.png', 'vendor/three.webgpu.min.js',
  ...fs.readdirSync(path.join(ROOT, 'vendor/fonts')).map(f => 'vendor/fonts/' + f)];
const files = [...new Set([...extra, ...refs])].sort();
const hash = crypto.createHash('sha1');
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(ROOT, f)));
const version = hash.digest('hex').slice(0, 10);
const sw = `// Generated by tools/build-web.cjs — do not edit by hand.
// Offline shell: precache every game file; network-first for same-origin so updates land, cache fallback offline.
const CACHE = 'ozymandosis-${version}';
const FILES = ${JSON.stringify(['./', ...files.map(f => './' + f)], null, 1)};
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.pathname === '/ws' || u.origin !== location.origin) return;
  e.respondWith(fetch(e.request).then(r => { if (r.ok) { const c = r.clone(); caches.open(CACHE).then(k => k.put(e.request, c)); } return r; })
    .catch(() => caches.match(e.request, { ignoreSearch: true }).then(m => m || caches.match('./index.html'))));
});
`;
fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
files.push('sw.js');
fs.rmSync(WWW, { recursive: true, force: true });
for (const f of files) { const d = path.join(WWW, f); fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(path.join(ROOT, f), d); }
let bytes = 0; for (const f of files) bytes += fs.statSync(path.join(WWW, f)).size;
console.log(`www/: ${files.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB, cache ${version}`);
