#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Bundles the living title (the word OZYMANDOSIS built from creatures) for pages
// outside the game: the website and the account portal. It is the game's own
// organ, culture and logo code, minified, plus a tiny mount script:
//   <canvas data-living-logo></canvas><script src="/living-logo.js"></script>
//   node tools/living-logo.cjs <out.js>
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const FILES = ['js/core/seed.js', 'js/core/util.js', 'js/data/organs.js', 'js/data/chassis.js', 'js/data/specials.js', 'js/data/techs.js', 'js/render/look.js', 'js/render/menuscene.js'];
const MOUNT = `
(function () {
  'use strict';
  var E = window.E;
  function mount(cv) {
    if (cv._living) return; cv._living = true;
    var logo = new E.LivingLogo(cv), still = matchMedia('(prefers-reduced-motion: reduce)').matches, seen = true, last = performance.now();
    if ('IntersectionObserver' in window) new IntersectionObserver(function (es) { seen = es[0].isIntersecting; }).observe(cv);
    // reduced motion: one composed frame, redrawn on resize
    if (still) { logo.t = 4; logo.frame(0.001); addEventListener('resize', function () { logo.frame(0); }); return; }
    (function loop(now) { requestAnimationFrame(loop); if (!seen || document.hidden) { last = now; return; } logo.frame((now - last) / 1000); last = now; })(last);
  }
  function all() { document.querySelectorAll('canvas[data-living-logo]').forEach(mount); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', all); else all();
  E.mountLivingLogos = all;
})();`;
function build() {
  const src = FILES.map(f => `// ${f}\n` + fs.readFileSync(path.join(ROOT, f), 'utf8')).join('\n;\n') + MOUNT;
  let out = src;
  try { out = require('esbuild').transformSync(src, { minify: true, legalComments: 'none', target: 'es2019' }).code; } catch (e) { /* no esbuild: ship it unminified */ }
  return '/* Ozymandosis living title. Generated by tools/living-logo.cjs. */\n' + out;
}
module.exports = { build, FILES };
if (require.main === module) {
  const out = process.argv[2]; if (!out) { console.error('usage: node tools/living-logo.cjs <out.js>'); process.exit(1); }
  fs.mkdirSync(path.dirname(out), { recursive: true }); fs.writeFileSync(out, build());
  console.log(`living-logo: ${out} (${Math.round(fs.statSync(out).size / 1024)} KB)`);
}
